app/dep/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404


urlpatterns = [
    path('', views.dashboard, name='home.dep'),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),

]

handler404 = views.Error404Views.as_view()

app/dep_mantenimiento/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404,handler403
from .views import Empleado_required, JefeDep_required, JefeMan_required, Solicitante_required, Sub_required, generar_pdf, vistas_solicitantes,vistas_Jefe_Departamento,vistas_Empleados,vistas_Subdirectora,vistas_Jefe_Mantenimiento

urlpatterns = [
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),
    # Validar el inicio del usuario
    path('Ingresar', views.inicio, name='inicio'),

    # Enlaces del Docente
    path('CargarSolicitudes/<int:id_Docente>/', Solicitante_required(views.vistas_solicitantes.obtener_solicitudes), name='obtener_solicitudes'),
    path('Inicio/Docente/<int:id>/', Solicitante_required(views.vistas_solicitantes.cargar_Inicio), name='inicio_docente'),
    path('Docente/Ver_Solicitud/<int:solicitud_id>/',Solicitante_required(views.vistas_solicitantes.cargar_Solicitud), name='solicitud_detallada'),
    
    # Enlaces del para guardar el formulario
    path('Formulario/Docente/<int:id_Docente>/', Solicitante_required(views.vistas_solicitantes.cargar_Formulario), name='formulario_docente'),
    path('guardar/<int:id_Docente>/', Solicitante_required(views.vistas_solicitantes.guardar_datos_Docente), name='guardar_formulario_Docente'),
    #Enlaces del para Editar el formulario
    path('Formulario/Docente/Solicitud/<int:idSolicitud>/', Solicitante_required(views.vistas_solicitantes.cargar_Formulario_Editar), name='formulario_editar'),
   
    # Enlaces del jefe de Departamento
    path('CargarSolicitudesJdep/<int:id_Jefe>/',JefeDep_required( views.vistas_Jefe_Departamento.obtener_solicitudes), name='obtener_solicitudes_jefe_departamento'),
    path('Inicio/Jefe_Departamento/<int:id>/',JefeDep_required( views.vistas_Jefe_Departamento.cargar_Inicio), name='inicio_jefe_departamento'),
    path('Formulario/Jefe_Departamento/<int:id_JefeDepartamento>/',JefeDep_required( views.vistas_Jefe_Departamento.cargar_Formulario), name='formulario_jefe_departamento'),
    path('Formulario/Jefe_Departamento/Solicitud/<int:idSolicitud>/',JefeDep_required( views.vistas_Jefe_Departamento.editar_Formulario), name='editar_Formulario'),
    path('Firmar_Formulario/Jefe_Departamento/Solicitud/<int:idSolicitud>/',JefeDep_required( views.vistas_Jefe_Departamento.firmarFormulario), name='firmar_Formulario'),
    path('Firmar_Formulario_VoBo/Jefe_Departamento/Solicitud/<int:idSolicitud>/',JefeDep_required( views.vistas_Jefe_Departamento.firmarFormularioVoBo), name='firmar_Formulario_VoBo'),
    path('Jefe_Departamento/Ver_Solicitud/<int:solicitud_id>/',JefeDep_required(views.vistas_Jefe_Departamento.cargar_Solicitud), name='solicitud_Detallada'),

    # Enlaces del Empleados
    path('CargarSolicitudesEmpleados/<int:idEmpleado>/', Empleado_required(views.vistas_Empleados.obtener_solicitudes), name='obtener_solicitudes_empleados'),
    path('Inicio/Empleado/<int:id>/', Empleado_required(views.vistas_Empleados.cargar_Inicio), name='inicio_empleado'),
    path('Firmar_Formulario/Empleado/Solicitud/<int:idSolicitud>/',Empleado_required( views.vistas_Empleados.firmarFormulario), name='firmar_Formulario_Empleado'),
    path('Empleado/Ver_Solicitud/<int:solicitud_id>/',Empleado_required(views.vistas_Empleados.cargar_Solicitud), name='sol_detallada'),
   # Enlaces del Subdirectora
    path('CargarSolicitudesSubdirectora/<int:idSubdirectora>/', Sub_required(views.vistas_Subdirectora.obtener_solicitudes), name='obtener_solicitudes_subdirectora'),
    path('Inicio/Subdirectora/<int:id>/', Sub_required(views.vistas_Subdirectora.cargar_Inicio), name='inicio_subdirector_servicios'),
    path('Formulario/Subdirectora/<int:idSubdirectora>/',Sub_required( views.vistas_Subdirectora.cargar_Formulario), name='formulario_Subdirectora'),
    path('Formulario/Subdirectora/Solicitud/<int:idSolicitud>/',Sub_required( views.vistas_Subdirectora.editar_Formulario), name='editarformulario'),
    path('Formulario_Peticion/Subdirectora/Solicitud/<int:idSolicitud>/',Sub_required( views.vistas_Subdirectora.peticion_formulario), name='peticion_formulario'),
    path('Firmar_Formulario_VoBo/Subdirectora/Solicitud/<int:idSolicitud>/',Sub_required( views.vistas_Subdirectora.firmarFormularioVoBo), name='firmarFormulario_VoBo'),
    path('Subdirectora/Ver_Solicitud/<int:solicitud_id>/',Sub_required(views.vistas_Subdirectora.cargar_Solicitud), name='solicitudDET'),
    path('Subdirectora/Historico_Empleados/',Sub_required(views.vistas_Subdirectora.cargarHistorico), name='cargarHistorico'),

   # Enlaces del Jefe de Mantenimiento
    path('CargarSolicitudesJefeMantenimiento/<int:idJefeMantenimiento>/', JefeMan_required(views.vistas_Jefe_Mantenimiento.obtener_solicitudes), name='obtener_solicitudes_jefe_mantenimiento'),
    path('Inicio/Jefe_Mantenimiento/<int:id>/', JefeMan_required(views.vistas_Jefe_Mantenimiento.cargar_Inicio), name='inicio_jefe_mantenimiento'),
    path('Formulario_Rechazar/Jefe_Mantenimiento/Solicitud/<int:idSolicitud>/',JefeMan_required( views.vistas_Jefe_Mantenimiento.rechazarFormulario), name='rechazarFormulario'),
     path('Formulario_Peticion/Jefe_Mantenimiento/Solicitud/<int:idSolicitud>/',JefeMan_required( views.vistas_Jefe_Mantenimiento.peticionFormulario), name='peticionFormulario'),
  
    path('Jefe_Mantenimiento/Ver_Solicitud/<int:solicitud_id>/',JefeMan_required(views.vistas_Jefe_Mantenimiento.cargar_Solicitud), name='solicitudDetallada'),
    # Eliminar solicitud
     path('eliminar-solicitud/<int:solicitud_id>/', views.eliminar_solicitud, name='eliminar_solicitud'),
     
   #Detalle solicitud
    path('CargarSolicitudDetallada/<int:solicitud_id>/', views.obtener_historial_solicitudes, name='cargar_historial_solicitudes'),
   #generar PDF 

   path('generar-pdf/<int:solicitud_id>/', generar_pdf, name='generar_pdf'),
   
]

handler404 = views.Error404Views.as_view()
handler403 = views.Error403Views.as_view()

app/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('main.urls')),
    path('dep/', include('dep.urls')),
    path('dep_alumnos/',include('dep_alumnos.urls')),
    path('mfa/', include('mfa.urls')),
    path('dep_mantenimiento/', include('dep_mantenimiento.urls')),
    path('admin/', admin.site.urls),
    
  
     #login
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/dep_mantenimiento/models.py
from django.utils import timezone

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
class trabajadores(models.Model):
    SEXO = (
        ('H', 'Hombre'),
        ('M', 'Mujer'),
    )
    Activo = (
        ('Activo', 'Activo'),
        ('Inactivo', 'Inactivo'),
    )

    Puestos={
        ('Subdirector','Subdirector/a'),
        ('Jefe','Jefe'),
        ('Docente','Docente'),
        ('Empleado','Empleado'),
        ('Secretario','Secretario/a')     
        
    }
    id=models.AutoField(primary_key=True)
    user_id=models.PositiveIntegerField( null=True, blank=True)
    nombres = models.CharField("Nombre(s)", max_length=40, db_column='nombres',blank=True, null=True)
    appaterno = models.CharField("Apellido Paterno", max_length=40, db_column='appaterno', blank=True, null=True)
    apmaterno = models.CharField("Apellido Materno", max_length=40, db_column='apmaterno', blank=True, null=True)
    activo = models.CharField(choices=Activo, max_length=15, db_column='activo', blank=True, null=True, default="activo")
    sexo = models.CharField("Sexo", max_length=1, choices=SEXO, db_column='sexo',blank=True, null=True)
    puesto=models.CharField(choices=Puestos,max_length=100,blank=True, null=True)# si es jefe, docente etc 
    departamento=models.CharField(max_length=100,blank=True, null=True)#y al departamento que pertenece 
    campus= models.PositiveIntegerField( null=True, blank=True)
    email = models.EmailField("Correo", max_length=100, db_column='email', blank=True, null=True)
    foto_Perfil = models.ImageField('Imagen de Perfil', upload_to='dep_mantenimiento/img/Foto_Perfil', blank=True, null= True)
    grupos = models.ManyToManyField('CustomGroup', related_name='trabajadores', blank=True)
    class Meta:
        app_label = 'dep_mantenimiento'
        db_table = 'trabajador'
        verbose_name = 'Perfil de trabajador'
        permissions = [
        ('view_mantenimiento_trabajador', 'Usuarios de Mantenimiento de Equipo pueden ver'),
        ('change_mantenimiento_trabajador', 'Usuarios de Mantenimiento de Equipo pueden editar'),
        ('view_all_trabajador', 'Usuarios Solcitantes pueden ver'),
        ('change_all_trabajador', 'Usuarios Solcitantes pueden editar'),
        ('add_all_trabajador', 'Usuarios Solcitantes pueden agregar'),
        ('delete_all_trabajador', 'Usuarios Solcitantes pueden borrar')
        ]
        
    def nombre_completo(self):
        nombre= self.nombres+" "+self.appaterno+" "+self.apmaterno
        return nombre
    
    def __str__(self):
        return self.nombre_completo()


    
class Solicitud_Mantenimiento(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    folio= models.CharField(default="Sin Sello",max_length=250,null=False,blank=True)
    area_solicitante= models.CharField(max_length=150,null=False,blank=True)
    responsable_Area= models.CharField(max_length=300,null=False,blank=True)
    servicos={
        ('Electrica','Electrica'),
        ('Herrería','Herrería'),
        ('Plomería','Plomería'),
        ('Pintura','Pintura'),
        ('Cañones','Cañones'),
        ('Pintarrón','Pintarrón'),
        ('Cerrajería','Cerrajería'),
        ('Otro','Otro')
        
    }
    
    tipo_servicio= models.CharField(choices=servicos,max_length=100,null=False,blank=True)
    descripcion= models.CharField(max_length=3000,null=False,blank=True)
    des_Serv_Realizado= models.CharField(max_length=3000,null=True,blank=True)
    des_Serv_no_Realizado= models.CharField(max_length=3000,null=True,blank=True)
    motv_rechazo= models.CharField(null=True,max_length=3000,blank=True)# cuando el jefe de mantenimiento rechaza la solicitud
    # cuando el jefe de mantenimiento pide algo a la subdirectora
    des_Peticion_Mat= models.CharField(max_length=3000,null=True,blank=True)# cuando se solicita material
    Mat_Rechazo= models.CharField(max_length=3000,null=True,blank=True) # cuando el material es rechazado por parte de la subsecretaria
    Mat_Resuelto= models.CharField(max_length=3000,null=True,blank=True) # cuando el material es resuelto por parte de la subsecretaria
    estatus={
        ('Enviado','Enviado'),#Solicitud enviada
        ('Pendiente','Pendiente'),#Solcitud sin asignar Empleados
        ('Realizado','Realizado'),#Solicitud completada
        ('Rechazado','Rechazado'),#Solicitud rechazada
        ('En_proceso','En proceso'),#Servicio en proceso con empleado asignado
        ('En_espera','En espera'),#Solicitud en espera por un evento o requerimiento
        ('Solicitud_Firmada','Firmado')#Solicitud firmada por el jefe o empleados
        
    }
    
    status= models.CharField(choices=estatus,max_length=50,blank=True)
    fecha= models.DateField(null=False,blank=True)
    hora= models.TimeField(null=False,blank=True)

    material_asignado= models.CharField(null=True,max_length=3000,blank=True)
    material_utilizado= models.CharField(null=True,max_length=3000,blank=True)
   
    
    
   # Relaciones con los trabajadores
    id_Trabajador = models.ForeignKey('trabajadores', on_delete=models.CASCADE, related_name='solicitudes_trabajador', null=True,blank=True)
    id_Jefe_Departamento = models.ForeignKey('trabajadores', on_delete=models.CASCADE, related_name='solicitudes_jefe_departamento', null=True,blank=True)
    id_Jefe_Mantenimiento = models.ForeignKey('trabajadores', on_delete=models.CASCADE, related_name='solicitudes_jefe_mantenimiento', null=True,blank=True)
    id_Subdirectora = models.ForeignKey('trabajadores', on_delete=models.CASCADE, related_name='solicitudes_subdirectora', null=True,blank=True)
    id_Empleado = models.ForeignKey('trabajadores', on_delete=models.CASCADE, related_name='solicitudes_empleado', null=True,blank=True)
    
    # Campos para firmas
    firma_Jefe_Departamento = models.BooleanField(default=False,blank=True)
    firma_Empleado = models.BooleanField(default=False,blank=True)
    firma_Jefe_VoBo = models.BooleanField(default=False,blank=True)
    resolvio = models.BooleanField(default=False,blank=True)
    # Imagenes de las firmas
    firma_Jefe_Departamento_img= models.ImageField(null=True,upload_to='dep_mantenimiento/img/Firmas/Jefe',blank=True)
    firma_Empleado_img= models.ImageField(null=True,upload_to='dep_mantenimiento/img/Firmas/Empleado',blank=True)
    firma_Jefe_VoBo_img= models.ImageField(null=True,upload_to='dep_mantenimiento/img/Firmas/VoBo',blank=True)
    
    #Funcion para ocultar la solicitud en vez de eliminarlo
    ocultar=models.BooleanField(default=False,blank=True,verbose_name='Ocultar_Solicitud')
    
    class Meta:
        app_label = 'dep_mantenimiento'
        db_table = 'solicitud_mantenimiento'
        verbose_name = 'Solicitud_de_mantenimiento'
        permissions = [
            #Permisos para Solicitante
            ('view_Solicitud_Solicitante', 'Solicitante ver'),
            ('change_Solicitud_Solicitante', 'Solicitante cambiar'),
            ('add_Solicitud_Solicitante', 'Solicitante agregar'),
            ('delete_Solicitud_Solicitante', 'Solicitante borrar'),
            
            #Permisos para jefeDep
            ('view_Solicitud_jefeDep', 'jefeDep ver'),
            ('change_Solicitud_jefeDep', 'jefeDep cambiar'),
            ('add_Solicitud_jefeDep', 'jefeDep agregar'),
            ('delete_Solicitud_jefeDep', 'jefeDep borrar'),    
            
            #Permisos para subdirector
            ('view_Solicitud_subdirector', 'subdirector ver'),
            ('change_Solicitud_subdirector', 'subdirector cambiar'),
            ('add_Solicitud_subdirector', 'subdirector agregar'),
            ('delete_Solicitud_subdirector', 'subdirector borrar'),
            
            
            #Permisos para jefe Mantenimiento
            ('view_Solicitud_jefe_Mantenimiento', 'jefMantenimiento ver'),
            ('change_Solicitud_jefe_Mantenimiento', 'jefMantenimiento cambiar'),
            
             #Permisos para empleado Mantenimiento
            ('view_Solicitud_empleado_Mantenimiento', 'empMantenimiento ver'),
            ('change_Solicitud_empleado_Mantenimiento', 'empMantenimiento cambiar'),
        ]# Modelo para los grupos personalizados



#Clase para imagenes
class imagenesEvidencias(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    solicitud = models.ForeignKey('Solicitud_Mantenimiento', on_delete=models.CASCADE, related_name='solicitud')
    #Se va subir varios archivos
    evidenciasIMG= models.ImageField(null=True,upload_to='dep_mantenimiento/img/Evidencias',blank=True)
    class Meta:
        app_label = 'dep_mantenimiento'
        db_table = 'Evidencias'
        verbose_name = 'Evidencias'      
        
class HistorialSolicitud(models.Model):
    id = models.AutoField(primary_key=True)
    solicitud = models.ForeignKey('Solicitud_Mantenimiento', on_delete=models.CASCADE, related_name='historial')
    # Campos para firmas
    firma_Jefe_Departamento = models.BooleanField(default=False,blank=True)
    firma_Empleado = models.BooleanField(default=False,blank=True)
    firma_Jefe_VoBo = models.BooleanField(default=False,blank=True)
    resolvio = models.BooleanField(default=False,blank=True)
    # Tiempo de creacion y actualizacion 
    fecha= models.DateField(default=timezone.now,null=False,blank=True)
    hora= models.TimeField(auto_now_add=True, null=False, blank=True)
    nuevo_status = models.CharField(choices=Solicitud_Mantenimiento.estatus, max_length=50)

    class Meta:
        app_label = 'dep_mantenimiento'
        db_table = 'historial_solicitud'
        verbose_name = 'Historial de Solicitud'        
        
@receiver(post_save, sender=Solicitud_Mantenimiento)
def crear_registro_historial(sender, instance, created, **kwargs):
    # Obtener la fecha actual
    fecha_actual = timezone.localtime(timezone.now())

   
    
    if created:

app/Empleados/forms.py
from django import forms
from dep_alumnos.models import tokens

class tokensForm(forms.ModelForm):
    class Meta:
        model = tokens
        exclude = ('idtoken','token_activo')
        
class SolicitudForm(forms.Form):
    fecha = forms.DateField(label="Fecha")
    folio = forms.CharField(label="Folio")
    area_solicitante = forms.CharField(label="Área Solicitante")
    responsable_area = forms.CharField(label="Responsable del Área")
    tipos_servicio = forms.ChoiceField(label="Tipo de Servicio", choices=[("tipo1", "Tipo 1"), ("tipo2", "Tipo 2"), ("tipo3", "Tipo 3")])
    descripcion = forms.CharField(label="Descripción del Servicio o Falla a Reparar", widget=forms.Textarea)

app/dep_mantenimiento/templates/dep_mantenimiento/layout/jMantenimiento/estatus.html
{% extends "dep_mantenimiento/layout/layout.html" %}
{% load static %}
{% block title %}<title>SARH | I.T. Morelia</title>{% endblock %}
{% block navpath %}
   <li class="breadcrumb-item"><a href="{% url 'home' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-grid-3x3-gap-fill" viewBox="0 0 16 16">
         <path d="M1 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2zM1 7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V7zM1 12a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-2z"/>
      </svg>
   </a></li>
   <li class="breadcrumb-item">
    <a href="{% url 'detalle_solicitud' solicitud_id=id %}">Detalles de la Solicitud</a>
</li>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
         <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
         <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
      </svg>
   </a></li>
   <li class="breadcrumb-item"> Navegación </li>
   <li class="breadcrumb-item"> directorio </li>

{% endblock %}
{% block content %}

<span class="align-middle">


   <!DOCTYPE html>
   <html>
   <head>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
       <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.12.313/pdf.min.js"></script>
       <title>visualizacion de la solicitud</title>
       <link rel="stylesheet" href="{% static "dep_mantenimiento/css/pages/jMantenimiento/estatus.css" %}">
       <link rel="stylesheet" href="{% static "dep_mantenimiento/css/pages/solicitante/formulario.css" %}">
    </head>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-VF43PqFHZBCZh4ysadDxE2NVWvwuCFVcRY+2Yv29O2hXPIghXJfVQfRYHA3wEY0tDpgmSRThyM9jT+GjRQtrNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   <body>
    
        <div class="top-bar">
            <a href="{% url 'inicio' %}">
            
                <button  class="boton-con-icono" style="width: 150px; height: 30px;">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-20 h-20">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75 3 12m0 0 3.75-3.75M3 12h18" />
                    </svg>   
                    anterior
                </button>
            </a>
        </div>


            <div style=" display: flex; align-items: flex-start;">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="w-3 h-3">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                </svg>              
                <div style="margin-left: 10px;">
                    <p style="margin: 0;">Solicitud de: {{ solicitud.id_Trabajador.nombre_completo }}</p>
                    <p style=" margin: 0;">Fecha de envío de la solicitud: {{ solicitud.fecha }}</p>
                </div>
            </div>

            <div style="margin-bottom: 40px;">
                <img src="{% static 'dep_mantenimiento/img/TecMor.png' %}" class="logo" style="width: 70px; height: auto; position: absolute; left: 5%;">
            </div>
            <h5 style="text-align: center;">Solicitud con folio: {{solicitud.folio}} de {{solicitud.id_Trabajador.nombre_completo}}</h5>

            <div style="background-color: #050506; 
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 3px 20px; 
            border-radius: 10px; /* Ajusta el valor según la curvatura que desees */
            max-width: calc(100% - 20%); /* 20px de espacio a la izquierda y 20px a la derecha */
            margin: 0 auto; /* Centra horizontalmente */">
            </div>



            

            


            <div class="container-fluid" id="ContenedorFormuario">
                <div class="mb-3">
                    <div class="d-flex align-items-center justify-content-between">
                        <div class="d-flex align-items-center">
                            <label for="id_fecha" class="form-label me-3">Fecha: {{ solicitud.fecha }}</label>
                           
                        </div>
                        <div class="d-flex align-items-center  ">
                            <label for="id_folio" class="form-label me-3">Folio: {{ solicitud.folio }}</label>
                            
                        </div>
                    </div>
                </div>
                <div class="mb-3 d-flex align-items-end justify-content-left">
                    <label for="id_area_solicitante" class="form-label me-4 " id="Area">Área Solicitante: {{ solicitud.area_solicitante }}</label>
                    
                </div>
                <div class="mb-3 d-flex align-items-end " >
                    <label for="id_responsable_area" class="form-label me-4 "id="RespArea">Responsable del Área: {{ solicitud.responsable_Area}}</label>
                    
                </div>
                <div class="mb-3 d-flex align-items-end ">
                    <label for="id_tipos_servicio" class="form-label me-4 " id="Tipo">Tipo de Servicio: {{ solicitud.tipo_servicio}}</label>
                    
                </div>
                
                <div class="mb-3 ">
                    <label for="id_descripcion" class="form-label ">Descripción del Servicio o Falla a Reparar: {{ solicitud.descripcion }}</label>
                    
                </div>
            </div>
<div>
    
    <form id="miFormulario" method="POST">
        {% csrf_token %}
        <div style="display: flex; align-items: center;">
            <label for="asignar" class="form-label">Asignar a:</label>
            {{ form.empleado }}
        </div>
        <div class="mb-3">
            <label for="id_asignar" class="form-label">Material a utilizar:</label>
            {{ form.material_Asignado }}
        </div>
        <input type="hidden" id="motivo_rechazo" name="motivo_rechazo">
        <div style="text-align: center;">
            <button type="button" id="btnEnviar" style="background-color: #041756; color: white; padding: .5px 40px; border: none; border-radius: 15px; cursor: pointer;">Aceptar</button>
            <button id="rechazar" style="background-color: #041756; color: white; padding: .5px 40px; border: none; border-radius: 15px; cursor: pointer;">Rechazar</button>
        </div>
    </form>
    <script src="{% static "dep_mantenimiento/js/jMantenimiento/estatus.js" %}" ></script>

            
            
    

            <br>
    </div>
    
    
</div>



<div id="historial-container">
    <!-- Aquí se mostrará el historial de solicitudes -->
</div>




<div>
    <p style="text-align: center;">Dar click en "Descargar solicitud" para obtener el documento en PDF</p>
    <button id="descargar-solicitud" style="background-color: #041756; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 0 auto; display: block;">Descargar solicitud</button>
</div>

<script>
    document.getElementById('descargar-solicitud').addEventListener('click', function() {
        alert('El archivo se ha descargado correctamente.');
    });
</script>

</div>
 
<script id="solicitud_id" data-solicitud-id="{{ id }}"></script>
    <script src="{% static "dep_mantenimiento/js/Detalles.js" %}" ></script>

    </body>
 </html>
   

   
   


</span>

      

{% endblock %}